[build-system]
requires = ["uv_build>=0.7.19,<0.8"]
build-backend = "uv_build"

[project]
name = "krcg-bot"
version = "4.5"
description = "Discord bot for VTES cards"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "lionelpx", email = "lionel.panhaleux@gmail.com" }]
maintainers = [{ name = "lionelpx", email = "lionel.panhaleux@gmail.com" }]
keywords = ["vampire", "vtes", "ccg", "discord", "bot"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Environment :: Plugins",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Games/Entertainment",
]
requires-python = ">=3.13"
dependencies = ["aiohttp", "hikari>=2.5,<3", "krcg>=5.9,<6", "unidecode"]

[dependency-groups]
dev = ["ipython", "mypy", "pytest", "ruff"]

[project.urls]
Homepage = "https://github.com/lionel-panhaleux/krcg-bot"
Repository = "https://github.com/lionel-panhaleux/krcg-bot"
Issues = "https://github.com/lionel-panhaleux/krcg-bot/issues"

[project.scripts]
krcg-bot = "krcg_bot:main"

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.mypy]
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
