# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          path: |
            .venv

      - name: Install dependencies
        run: uv sync --dev

      - name: Quality checks
        run: uv run just quality

      - name: Test
        run: uv run just test
